import type { NextPage } from "next";
import Head from "next/head";
import LeftPane from "../components/LeftPane";
import NFTCard from "../components/NFTCard";

const Home: NextPage = () => {
    return (
        <div className="bg-teal-50 text-gray-900">
            {/* <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head> */}

            <main className="grid grid-cols-3 gap-x-5">
                <LeftPane />
                <div className="col-span-2 py-20 pr-10">
                    <div className="grid grid-cols-3 gap-x-6 gap-y-8">
                        <NFTCard />
                        <NFTCard />
                        <NFTCard />
                        <NFTCard />
                        <NFTCard />
                        <NFTCard />
                        <NFTCard />
                        <NFTCard />
                        <NFTCard />
                        <NFTCard />
                    </div>
                </div>
            </main>
        </div>
    );
};

export default Home;
