/* eslint-disable react-hooks/exhaustive-deps */
/* eslint-disable @next/next/no-img-element */
import type { NextPage } from "next";
import Head from "next/head";
import { ReactNode, useEffect, useState } from "react";
import LeftPane from "../components/LeftPane";
import RightPane from "../components/RightPane";
import { View, NFT_API, DAO_API } from "../types/enums";
import { NFT } from "../types/NFT";
import axios from "axios";
import { useNetworkContext } from "../contexts/Network";
import { useAddressContext } from "../contexts/Address";
import { Collection } from "../types/Collection";
import { Transaction } from "../types/Transation";
import { useLoadingContext } from "../contexts/Loading";
import NFTs_Collections from "../components/Views/NFTs_Collections";
import NFTs_NFTs from "../components/Views/NFTs_NFTs";
import NFTs_Transactions from "../components/Views/NFTs_Transactions";
import Empty from "../components/Views/Empty";
import UC from "../components/Views/UC";

const Home: NextPage = () => {
    const { network } = useNetworkContext();
    const { address } = useAddressContext();
    const { loading, setLoading } = useLoadingContext();

    const [view, setView] = useState(View.NFTs);
    const [api, setApi] = useState<NFT_API | DAO_API>(NFT_API.NFTs);
    const [rightPaneView, setRightPaneView] = useState<ReactNode>();
    const [nfts, setNfts] = useState<NFT[]>();
    const [collections, setCollections] = useState<Collection[]>();
    const [transactions, setTransactions] = useState<Transaction[]>();

    const updateRightPaneView = () => {
        if (!loading && nfts && collections && transactions)
            switch (view) {
                case View.NFTs:
                    switch (api) {
                        case NFT_API.NFTs:
                            return nfts.length > 0 ? (
                                <NFTs_NFTs nfts={nfts} />
                            ) : (
                                <Empty />
                            );
                        case NFT_API.Collections:
                            return collections.length > 0 ? (
                                <NFTs_Collections collections={collections} />
                            ) : (
                                <Empty />
                            );
                        case NFT_API.Transactions:
                            return transactions.length > 0 ? (
                                <NFTs_Transactions
                                    transactions={transactions}
                                />
                            ) : (
                                <Empty />
                            );
                    }
                case View.DAOs:
                    return <UC />;
            }
    };

    const updateNfts = async () => {
        const data = (await (
            await axios.get(`/api/nfts/${network}/${address}`)
        ).data) as NFT[];
        setNfts(data);
    };

    const updateCollections = async () => {
        const data = await (
            await axios.get(`/api/nft_collections/${network}/${address}`)
        ).data;
        setCollections(data);
    };

    const updateTransactions = async () => {
        const data = await (
            await axios.get(`/api/nfts/transactions/${network}/${address}`)
        ).data;
        setTransactions(data);
    };

    const updateData = async () => {
        console.log("updating");
        setLoading(true);
        await updateNfts();
        await updateCollections();
        await updateTransactions();
        setLoading(false);
        console.log("updated");
    };

    useEffect(() => {
        if (!loading) updateData();
    }, []);

    useEffect(() => {
        setRightPaneView(updateRightPaneView());
    }, [view, api, nfts, collections, transactions]);

    return (
        <div className="relative bg-teal-50 text-gray-900">
            {/* <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head> */}

            <main className="grid grid-cols-3">
                <LeftPane
                    view={view}
                    api={api}
                    setView={setView}
                    setApi={setApi}
                    handleUpdateData={() => {
                        if (!loading) updateData();
                    }}
                />
                <RightPane>{rightPaneView}</RightPane>
            </main>
        </div>
    );
};

export default Home;
